### ISSUE TITLE
Unable to setup environment

### ISSUE THREAD

**Issue by mreid-tt** [SynoCommunity/spkrepo#108]
I tried to setup this repo in a clean Ubuntu Server 22.04.3 environment but encountered the following:

```
$ sudo apt install python3-poetry
[...]
$ python3 -V
Python 3.10.12
$ poetry -V
Poetry version 1.1.12
$ git clone https://github.com/SynoCommunity/spkrepo
Cloning into 'spkrepo'...
remote: Enumerating objects: 776, done.
remote: Counting objects: 100% (235/235), done.
remote: Compressing objects: 100% (116/116), done.
remote: Total 776 (delta 136), reused 209 (delta 119), pack-reused 541
Receiving objects: 100% (776/776), 627.79 KiB | 2.06 MiB/s, done.
Resolving deltas: 100% (416/416), done.
$ cd spkrepo/
$ poetry install
Creating virtualenv spkrepo-DHYObr5C-py3.10 in /home/user/.cache/pypoetry/virtualenvs
Installing dependencies from lock file

Package operations: 90 installs, 0 updates, 1 removal

  • Removing setuptools (65.5.0)
  • Installing markupsafe (2.1.1)
  • Installing certifi (2021.10.8)
  • Installing charset-normalizer (2.0.12)
  • Installing click (8.0.4)
  • Installing greenlet (1.1.2)
  • Installing idna (3.3)
  • Installing itsdangerous (2.1.1)
  • Installing jinja2 (3.0.3)
  • Installing pycparser (2.21)
  • Installing pyparsing (3.0.7)
  • Installing pytz (2021.3)
  • Installing six (1.16.0)
  • Installing urllib3 (1.26.8)
  • Installing werkzeug (2.2.2)
  • Installing alabaster (0.7.12)
  • Installing babel (2.9.1)
  • Installing blinker (1.4): Failed

  EnvCommandError

  Command ['/home/mreid/.cache/pypoetry/virtualenvs/spkrepo-DHYObr5C-py3.10/bin/pip', 'install', '--no-deps', '/home/mreid/.cache/pypoetry/artifacts/74/95/38/499fa961f5a9f793cda437450852378acc1aed0f7263ea12d71017fdb6/blinker-1.4.tar.gz'] errored with the following return code 1, and output: 
  Processing /home/mreid/.cache/pypoetry/artifacts/74/95/38/499fa961f5a9f793cda437450852378acc1aed0f7263ea12d71017fdb6/blinker-1.4.tar.gz
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'error'
    error: subprocess-exited-with-error
    
    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [1 lines of output]
        ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: metadata-generation-failed
  
  × Encountered error while generating package metadata.
  ╰─> See above for output.
  
  note: This is an issue with the package mentioned above, not pip.
  hint: See above for details.
  

  at /usr/lib/python3/dist-packages/poetry/utils/env.py:1183 in _run
      1179│                 output = subprocess.check_output(
      1180│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1181│                 )
      1182│         except CalledProcessError as e:
    → 1183│             raise EnvCommandError(e, input=input_)
      1184│ 
      1185│         return decode(output)
      1186│ 
      1187│     def execute(self, bin, *args, **kwargs):

  • Installing cffi (1.15.0)
  • Installing distlib (0.3.4)
  • Installing dnspython (2.2.1)
  • Installing docutils (0.16)
  • Installing filelock (3.6.0)
  • Installing flask (2.2.2)
  • Installing imagesize (1.3.0)
  • Installing mako (1.2.0)
  • Installing mkdocs-material-extensions (1.1)
  • Installing packaging (21.3)
  • Installing platformdirs (2.5.1)
  • Installing pygments (2.11.2)
  • Installing python-dateutil (2.8.2)
  • Installing requests (2.27.1)
  • Installing snowballstemmer (2.2.0)
  • Installing sphinxcontrib-applehelp (1.0.2)
  • Installing sphinxcontrib-devhelp (1.0.2)
  • Installing sphinxcontrib-htmlhelp (2.0.0)
  • Installing sphinxcontrib-jsmath (1.0.1)
  • Installing sphinxcontrib-qthelp (1.0.3)
  • Installing sphinxcontrib-serializinghtml (1.1.5)
  • Installing sqlalchemy (1.4.32)
  • Installing text-unidecode (1.3)
  • Installing webencodings (0.5.1)
  • Installing wrapt (1.14.0)
  • Installing wtforms (3.0.1)
```

Any ideas on how to resolve this?

**Comment by publicarray** [comment]
Looks like setup tools is no longer installed by default. Try adding it

`poetry add setuptools`

https://python-poetry.org/docs/configuration/

> For environments using python 3.12 or later, virtualenv defaults to not installing setuptools when creating a virtual environment. In such environments this poetry configuration option therefore has no effect: setuptools is not installed either way. If your project relies on setuptools, you should declare it as a dependency

**Comment by mreid-tt** [comment]
@publicarray, thanks for this. I had to do a bit more for that to work though since running that on its own got pretty much the same error. However this seemed to work:

```
$ sudo apt install python3.10-venv
[...]
$ python3 -m venv .venv
$ poetry add setuptools
Using version ^69.0.3 for setuptools

Updating dependencies
Resolving dependencies... (0.3s)

Package operations: 48 installs, 0 updates, 0 removals

  • Installing blinker (1.4)
  • Installing alembic (1.7.6)
  • Installing cfgv (3.3.1)
  • Installing attrs (21.4.0)
  • Installing bcrypt (3.2.0)
  • Installing bleach (5.0.1)
  • Installing aniso8601 (9.0.1)
  • Installing deprecated (1.2.13)
  • Installing email-validator (1.1.3)
  • Installing faker (4.18.0)
  • Installing flask-login (0.6.2)
  • Installing flask-mailman (0.3.0)
  • Installing flask-principal (0.4.0)
  • Installing flask-sqlalchemy (2.5.1)
  • Installing flask-wtf (1.0.0)
  • Installing identify (2.4.11)
  • Installing iniconfig (1.1.1)
  • Installing nodeenv (1.6.0)
  • Installing passlib (1.7.4)
  • Installing pluggy (1.0.0)
  • Installing py (1.11.0)
  • Installing pyyaml (6.0)
  • Installing speaklater (1.3)
  • Installing sphinx (3.5.4)
  • Installing sqlalchemy-utils (0.38.3)
  • Installing toml (0.10.2)
  • Installing virtualenv (20.13.3)
  • Installing configparser (5.2.0)
  • Installing factory-boy (2.12.0)
  • Installing flask-admin (1.6.0)
  • Installing flask-babelex (0.9.4)
  • Installing flask-caching (1.10.1)
  • Installing flask-cli (0.4.0)
  • Installing flask-debugtoolbar (0.11.0)
  • Installing flask-mail (0.9.1)
  • Installing flask-migrate (3.1.0)
  • Installing flask-restful (0.3.9)
  • Installing flask-security-too (5.0.2)
  • Installing flask-testing (0.8.1)
  • Installing ipaddress (1.0.23)
  • Installing lxml (4.8.0)
  • Installing mock (4.0.3)
  • Installing pillow (8.4.0)
  • Installing pre-commit (2.17.0)
  • Installing pytest (6.2.5)
  • Installing python-gnupg (0.4.8)
  • Installing redis (4.1.4)
  • Installing sphinx-rtd-theme (0.4.3)
```

I was able to start building out the environment...

```
$ poetry shell
Spawning shell within /home/user/Documents/spkrepo/.venv
[...]
$ python manage.py create
/home/mreid/Documents/spkrepo/spkrepo/models.py:499: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
  download_count = db.column_property(
/home/mreid/Documents/spkrepo/spkrepo/models.py:505: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
  recent_download_count = db.column_property(
/home/mreid/Documents/spkrepo/.venv/lib/python3.10/site-packages/flask_caching/__init__.py:201: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn(
2023-12-28 20:51:10,562 INFO sqlalchemy.engine.Engine BEGIN (implicit)
[...]
2023-12-28 20:51:10,582 INFO sqlalchemy.engine.Engine COMMIT
```

But then I got this:

```
$ python manage.py populate
/home/mreid/Documents/spkrepo/spkrepo/models.py:499: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
  download_count = db.column_property(
/home/mreid/Documents/spkrepo/spkrepo/models.py:505: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
  recent_download_count = db.column_property(
/home/mreid/Documents/spkrepo/.venv/lib/python3.10/site-packages/flask_caching/__init__.py:201: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn(
Traceback (most recent call last):
  File "/home/mreid/Documents/spkrepo/manage.py", line 248, in <module>
    cli()
  File "/home/mreid/Documents/spkrepo/.venv/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/mreid/Documents/spkrepo/.venv/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/mreid/Documents/spkrepo/.venv/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mreid/Documents/spkrepo/.venv/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mreid/Documents/spkrepo/.venv/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/mreid/Documents/spkrepo/.venv/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/mreid/Documents/spkrepo/.venv/lib/python3.10/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/mreid/Documents/spkrepo/.venv/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/mreid/Documents/spkrepo/manage.py", line 89, in populate
    nzbget_package = PackageFactory(name="nzbget")
  File "/home/mreid/Documents/spkrepo/.venv/lib/python3.10/site-packages/factory/base.py", line 46, in __call__
    return cls.create(**kwargs)
  File "/home/mreid/Documents/spkrepo/.venv/lib/python3.10/site-packages/factory/base.py", line 564, in create
    return cls._generate(enums.CREATE_STRATEGY, kwargs)
  File "/home/mreid/Documents/spkrepo/.venv/lib/python3.10/site-packages/factory/base.py", line 501, in _generate
    return step.build()
  File "/home/mreid/Documents/spkrepo/.venv/lib/python3.10/site-packages/factory/builder.py", line 301, in build
    self.factory_meta.use_postgeneration_results(
  File "/home/mreid/Documents/spkrepo/.venv/lib/python3.10/site-packages/factory/base.py", line 321, in use_postgeneration_results
    self.factory._after_postgeneration(
  File "/home/mreid/Documents/spkrepo/spkrepo/tests/common.py", line 160, in _after_postgeneration
    screenshot.save(create_image("Screenshot %s" % obj.name))
  File "/home/mreid/Documents/spkrepo/spkrepo/tests/common.py", line 561, in create_image
    process = subprocess.Popen(command, stdout=subprocess.PIPE)
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'convert'
```

Any thoughts?

**Comment by publicarray** [comment]
Hm, I'm not sure, but I got a working build with the following: (I'm on manjaro)

```
pacman -S python-pipx
pipx ensurepath
pipx install poetry
pyenv init
pyenv install 3.10.12
pyenv local 3.10.12
poetry env use 3.10.12
```

**Comment by mreid-tt** [comment]
@publicarray, that's the same create that works fine for me. did you get this to work for you?

```
python manage.py populate
```

**Comment by publicarray** [comment]
Sorry I miss read it, yes seems to work:

```
❯ python manage.py populate
/home/seb/git/spkrepo/spkrepo/models.py:499: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
  download_count = db.column_property(
/home/seb/git/spkrepo/spkrepo/models.py:505: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
  recent_download_count = db.column_property(
/home/seb/.cache/pypoetry/virtualenvs/spkrepo-4s3rbOEh-py3.10/lib/python3.10/site-packages/flask_caching/__init__.py:201: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn(
2023-12-29 13:18:51,383 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-12-29 13:18:51,384 INFO sqlalchemy.engine.Engine SELECT service.id AS service_id, service.code AS service_code 
FROM service
2023-12-29 13:18:51,384 INFO sqlalchemy.engine.Engine [generated in 0.00007s] ()
2023-12-29 13:18:51,385 INFO sqlalchemy.engine.Engine SELECT language.id AS language_id, language.code AS language_code, language.name AS language_name 
FROM language 
WHERE language.code = ?
 LIMIT ? OFFSET ?
2023-12-29 13:18:51,385 INFO sqlalchemy.engine.Engine [generated in 0.00007s] ('enu', 1, 0)
2023-12-29 13:18:51,386 INFO sqlalchemy.engine.Engine SELECT language.id AS language_id, language.code AS language_code, language.name AS language_name 
FROM language 
WHERE language.code = ?
 LIMIT ? OFFSET ?
2023-12-29 13:18:51,386 INFO sqlalchemy.engine.Engine [cached since 0.0005487s ago] ('enu', 1, 0)
2023-12-29 13:18:51,407 INFO sqlalchemy.engine.Engine SELECT service.id AS service_id, service.code AS service_code 
FROM service
2023-12-29 13:18
[...]
```

**Comment by publicarray** [comment]
Ah sorry I just found out what the error is convert is from ImageMagick you need to have it installed to convert the icons

**Comment by publicarray** [comment]
@mreid-tt I have updated the README to include Image Magic

**Comment by mreid-tt** [comment]
@publicarray, thanks for that. I got a bit further after this:

```
$  sudo apt install imagemagick
[...]
$ python manage.py populate
/home/mreid/Documents/spkrepo/spkrepo/models.py:499: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
  download_count = db.column_property(
/home/mreid/Documents/spkrepo/spkrepo/models.py:505: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
  recent_download_count = db.column_property(
/home/mreid/Documents/spkrepo/.venv/lib/python3.10/site-packages/flask_caching/__init__.py:201: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn(
2023-12-28 22:33:24,732 INFO sqlalchemy.engine.Engine BEGIN (implicit)
[...]
2023-12-28 22:33:25,747 INFO sqlalchemy.engine.Engine COMMIT
```

```
$ python manage.py user create -u Admin -e admin@admin.adm -p adminadmin
/home/mreid/Documents/spkrepo/spkrepo/models.py:499: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
  download_count = db.column_property(
/home/mreid/Documents/spkrepo/spkrepo/models.py:505: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
  recent_download_count = db.column_property(
/home/mreid/Documents/spkrepo/.venv/lib/python3.10/site-packages/flask_caching/__init__.py:201: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn(
2023-12-28 22:34:12,235 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2023-12-28 22:34:12,236 INFO sqlalchemy.engine.Engine INSERT INTO user (username, email, password, api_key, github_access_token, fs_uniquifier, active, confirmed_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
2023-12-28 22:34:12,236 INFO sqlalchemy.engine.Engine [generated in 0.00009s] ('Admin', 'admin@admin.adm', '$6$rounds=656000$rN.QtTFagdi6OJiv$csjEtZ.o5ZPFVuPtTVJNryaEoPckMAFkmsb.tXrJBKNcE75DZzd8guLtEjNXC3r5A28gdCABV6q/Wom2Y7eHk/', None, None, 'd4e1e23a2b6d4449872f2d95140bb64d', 1, '2023-12-28 22:34:11.709289')
2023-12-28 22:34:12,236 INFO sqlalchemy.engine.Engine COMMIT
User created successfully.
{
    "active": true,
    "confirmed_at": "2023-12-28T22:34:11.709289",
    "email": "admin@admin.adm",
    "password": "****",
    "username": "Admin"
}
``` 

But then I have this issue:

```
$ python manage.py roles add admin@admin.adm admin
/home/mreid/Documents/spkrepo/spkrepo/models.py:499: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
  download_count = db.column_property(
/home/mreid/Documents/spkrepo/spkrepo/models.py:505: SAWarning: implicitly coercing SELECT object to scalar subquery; please use the .scalar_subquery() method to produce a scalar subquery.
  recent_download_count = db.column_property(
/home/mreid/Documents/spkrepo/.venv/lib/python3.10/site-packages/flask_caching/__init__.py:201: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn(
Usage: manage.py roles add [OPTIONS] USER ROLE
Try 'manage.py roles add --help' for help.

Error: User not found.
```

**Comment by publicarray** [comment]
It probably comes from this commit 43e52667267b773353462af5fad613f05fd39d7a

We could revert this as the project was picked up again
![image](https://github.com/SynoCommunity/spkrepo/assets/5497998/b8964e97-cd57-467b-8025-caea5f1577b1)

**Comment by publicarray** [comment]
https://flask-security-too.readthedocs.io/en/stable/changelog.html#version-3-3-0

**Comment by publicarray** [comment]
Unfortunately I'm experienced with the flask ecosystem. This can take some for me/someone to learn and fix the commands.

**Comment by publicarray** [comment]
For now, you can open the database and add permissions manually:
![image](https://github.com/SynoCommunity/spkrepo/assets/5497998/ce0a377e-5df6-4fc9-8a1e-349e22c2f991)

**Comment by publicarray** [comment]
You can also look at the refactor #102 from @Diaoul which should fix these commands

**Comment by mreid-tt** [comment]
So I re-did the installation from scratch using a method closer to your example but the same issue with the DB user:

```
$ sudo apt update && sudo apt upgrade
$ sudo apt install imagemagick
$ sudo apt install make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev
$ curl https://pyenv.run | bash
$ echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n eval "$(pyenv init -)"\nfi' >> ~/.bashrc
$ exec "$SHELL"
$ sudo apt install pipx
$ pipx ensurepath
$ pipx install poetry
$ pyenv init
```
```
$ pyenv install 3.10.12
Downloading Python-3.10.12.tar.xz...
-> https://www.python.org/ftp/python/3.10.12/Python-3.10.12.tar.xz
Installing Python-3.10.12...
Installed Python-3.10.12 to /home/mreid/.pyenv/versions/3.10.12
```
```
$ pyenv local 3.10.12
$ git clone https://github.com/SynoCommunity/spkrepo
$ cd spkrepo/
$ poetry env use 3.10.12
Creating virtualenv spkrepo-DHYObr5C-py3.10 in /home/mreid/.cache/pypoetry/virtualenvs
Using virtualenv: /home/mreid/.cache/pypoetry/virtualenvs/spkrepo-DHYObr5C-py3.10
$ poetry install
Installing dependencies from lock file
[...]
Installing the current project: spkrepo (0.2.3)
```
```
$ poetry shell
(spkrepo-py3.10) $ python manage.py create
(spkrepo-py3.10) $ python manage.py populate
(spkrepo-py3.10) $ python manage.py user create -u Admin -e admin@admin.adm -p adminadmin
(spkrepo-py3.10) $ python manage.py roles add admin@admin.adm admin
[...]
Error: User not found.
```

**Comment by mreid-tt** [comment]
> For now, you can open the database and add permissions manually: ![image](https://private-user-

Thanks for that. I've installed sqlitebrowser and added three rows to the user_role table. I did have to change the email address of the admin user from admin@admin.adm to admin@admin.com since the login UI rejected the email address as invalid. In the end it's up and running now so I can do some local testing of some of the changes we need. I am pleased to say that the code I uploaded previously to hide deactivated packages does work. I'll see if we can extend that to perhaps have it as a user toggle to show or hide them.

**Comment by mreid-tt** [comment]
> @mreid-tt I have updated the README to include Image Magic

Cool, but I think you've spelled it incorrectly. The command I used was:

```
sudo apt install imagemagick
```

Before I close this ticket, if I start experimenting with the code, can I just make changes to it in the virtual environment created by `poetry shell` or do I need to make another `poetry install` to see experiments in action?

**Comment by mreid-tt** [comment]
> You can also look at the refactor #102 from @Diaoul which should fix these commands

I believe this is what I should be working on and I'll close this issue in light of that PR. Also, I had to commit a merge branch because the updated README caused a conflict. So I don't think updating the README further would be a good idea.

**Comment by publicarray** [comment]
> README caused a conflic

This would only be an issue if you also edited the README file at the sames lines that I did (still solvable manually while others can be solved automatically). Before making changes you can pull the changes from master first or when creating your own branch, I usually rebase from master occasionally to reduce the work later. I use sublime merge or Microsoft code to deal with conflicts, some can be dealt with automatically. Conflicts are going to happen occasionally with distributed development, and it is good to be able to deal with them when they pop up. In general, I do not believe that stopping development to a file is a viable a solution to this problem. But I do not intend to make any more changes if it helps.
