### ISSUE TITLE
Publish fails with 413 Request Entity Too Large 

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spkrepo#47]
Any publish fails with
```
HTTP/1.1 413 Request Entity Too Large
Connection: close
Content-Length: 184
Content-Type: text/html
Date: Wed, 08 Jul 2020 21:02:36 GMT
Server: nginx/1.17.10

<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.17.10</center>
</body>
</html>
```

I have tried to add following statement to `nginx.conf` file
```
    client_max_body_size           32M; 
```

And reload nginx configuration in docker container (I have no idea how to restart the docker compose processes)
```
root@vps-b34822e4:/home/yma/logs# docker container exec 7a8b8dba8ce9 nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
root@vps-b34822e4:/home/yma/logs# docker container exec 7a8b8dba8ce9 nginx -s reload
f2020/07/08 21:02:08 [notice] 68#68: signal process started
root@vps-b34822e4:/home/yma/logs# docker logs --tail=50  -f --details 7a8b8dba8ce9 | tee > nginx-logs.log
 2020/07/08 21:02:36 [error] 74#74: *14480791 client intended to send too large body: 7249920 bytes, client: 188.154.181.155, server: api.synocommunity.com, request: "POST /packages HTTP/1.1", host: "api.synocommunity.com"
```

But without effect or success. May you please help to get it work?

**Comment by Diaoul** [comment]
Can you retry? I added `client_max_body_size` to the location directive in addition to `server`.

**Comment by Diaoul** [comment]
+ also in `http` block

**Comment by ymartin59** [comment]
`publish` target only use https. Probably it gets further as now it fails with `HTTP/1.1 500 INTERNAL SERVER ERROR`

**Comment by Diaoul** [comment]
```bash
docker logs synocommunity_app_1
```
shows many of:
```
[2020-07-12 16:52:27,174] ERROR in app: Exception on /packages [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/src/app/spkrepo/views/api.py", line 47, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/src/app/spkrepo/views/api.py", line 103, in post
    spk = SPK(io.BytesIO(request.data))
  File "/usr/src/app/spkrepo/utils.py", line 192, in __init__
    except UnicodeDecodeError:
  File "/usr/local/lib/python3.8/configparser.py", line 723, in read_string
    self.read_file(sfile, source)
  File "/usr/local/lib/python3.8/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/local/lib/python3.8/configparser.py", line 1082, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '<string>', line: 1
'{\n'
```

So it seems it's getting JSON instead of expected ini format.

**Comment by Diaoul** [comment]
I close this as this is fixed
